-- UOMe Database Schema
-- Set timezone for this session (should match DB_TIMEZONE environment variable)
SET timezone = 'Australia/Melbourne';

-- Drop tables if they exist (for development)
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS leave_records CASCADE;
DROP TABLE IF EXISTS public_holidays CASCADE;
DROP TABLE IF EXISTS closed_dates CASCADE;
DROP TABLE IF EXISTS birthdays CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Users table
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  two_factor_secret VARCHAR(255),
  two_factor_enabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Transactions table
CREATE TABLE transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  from_user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  to_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount DECIMAL(10, 2) NOT NULL CHECK (amount > 0),
  date TIMESTAMPTZ NOT NULL,
  description TEXT,
  transaction_type VARCHAR(20) NOT NULL DEFAULT 'personal' CHECK (transaction_type IN ('personal', 'company')),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT different_users CHECK (from_user_id IS NULL OR from_user_id != to_user_id),
  CONSTRAINT company_transaction_check CHECK (
    (transaction_type = 'personal' AND from_user_id IS NOT NULL) OR
    (transaction_type = 'company' AND from_user_id IS NULL)
  )
);

-- Leave records table
CREATE TABLE leave_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  business_days INTEGER NOT NULL CHECK (business_days > 0),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT valid_date_range CHECK (start_date <= end_date)
);

-- Public holidays table
CREATE TABLE public_holidays (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Closed dates table
CREATE TABLE closed_dates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT valid_closed_date_range CHECK (start_date <= end_date)
);

-- Birthdays table
CREATE TABLE birthdays (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  date_of_birth DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX idx_transactions_from_user ON transactions(from_user_id);
CREATE INDEX idx_transactions_to_user ON transactions(to_user_id);
CREATE INDEX idx_transactions_date ON transactions(date);
CREATE INDEX idx_leave_records_user ON leave_records(user_id);
CREATE INDEX idx_leave_records_dates ON leave_records(start_date, end_date);
CREATE INDEX idx_public_holidays_date ON public_holidays(date);
CREATE INDEX idx_closed_dates_range ON closed_dates(start_date, end_date);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for updated_at
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_transactions_updated_at BEFORE UPDATE ON transactions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_leave_records_updated_at BEFORE UPDATE ON leave_records
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_public_holidays_updated_at BEFORE UPDATE ON public_holidays
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_closed_dates_updated_at BEFORE UPDATE ON closed_dates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_birthdays_updated_at BEFORE UPDATE ON birthdays
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert default users (passwords will be hashed in application)
-- Note: These are placeholder entries. Actual password hashes should be generated by the application
INSERT INTO users (username, password_hash, two_factor_enabled) VALUES
  ('Leva', '$2b$10$placeholder1', FALSE),
  ('Danik', '$2b$10$placeholder2', FALSE);

COMMENT ON TABLE users IS 'Stores user authentication and profile information';
COMMENT ON TABLE transactions IS 'Records money transfers between users';
COMMENT ON TABLE leave_records IS 'Tracks employee leave with business day calculations';
COMMENT ON TABLE public_holidays IS 'Stores nationally recognized holidays';
COMMENT ON TABLE closed_dates IS 'Stores company closure periods';
COMMENT ON TABLE birthdays IS 'Stores employee birthdays for age calculation';
